#!/bin/sh

case "$1" in
  start)
        echo 0 > /sys/class/graphics/fbcon/cursor_blink
        /usr/bin/fbv /usr/share/pixmaps/avec.bmp
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        echo "OK"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
